{{- if .Values.route.enabled -}}
{{- $fullName := include "code-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: code-server
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ $fullName }}
  port:
    targetPort: {{ $svcPort }}
{{- end }}
